apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: demo-app
type: Opaque
stringData:
  DB_USER: demouser
  DB_PASS: demopass
  DB_NAME: demodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-app
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  SPRING_PROFILES_ACTIVE: docker
